import "./globals.css";
import Header from "../components/layout/header";
import { AlertProvider } from "@/contexts/alert-context";
import { WebSocketProvider } from "@/contexts/websocket-context";

export const metadata = {
  title: "Woori-CodeShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning className="overflow-hidden">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-LRSD0EJFQG"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-LRSD0EJFQG');
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                  c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                  t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                  y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "qgurtqpcgg");
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            `,
          }}
        />
        <meta name="grammarly-verification" content="off" />
        <style>
          {`
            ::-webkit-scrollbar {
              display: none;
            }
            * {
              -ms-overflow-style: none;
              scrollbar-width: none;
            }
          `}
        </style>
      </head>
      <body
        className="bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 overflow-hidden"
        suppressHydrationWarning
      >
        <AlertProvider>
          <Header />
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}
